### ISSUE TITLE
package is distributing typescript files

### ISSUE THREAD

**Issue by nopeless** [falsandtru/spica#1]
Not sure if it is intentional, but your package has typescript files. I see that you are waiting for

https://github.com/webpack/webpack/issues/5866

Can I have a clue on whats going on? thanks

**Comment by falsandtru** [comment]
Webpack duplicates dependent local modules for each module. To avoid this redundancy, spica is currently intended to be transpiled with dependent products by TypeScript. Code of another my package such as typed-dom or dw-cache would be an example of this usage. If you just want to use spica/cache or spica/clock, you can use the individualized package:

https://www.npmjs.com/package/dw-cache
https://www.npmjs.com/package/bclock

**Comment by nopeless** [comment]
Ok, I see your reasoning, but I am still curious about two points

1. If you bundle it using esm, wouldn't webpack automatically treeshake the js files? In other words, bundle spica as a whole, and let the project determine which modules to bundle

2. I am using Spica in a node environment (w/ esm), and reducing bundle size isn't my concern at the moment. Considering that many node users I know still use JS and don't know how bundlers work, I think it might be useful to at least give a compiled js distribution for those people

Thanks for the fast response

**Comment by falsandtru** [comment]
I'm not using esm and not sure about esm but webpack output duplicate js code with the current commented out config in https://github.com/falsandtru/spica/blob/master/webpack.config.js. Any solutions to output .js files per module?

**Comment by nopeless** [comment]
> I'm not using esm and not sure about esm but webpack output duplicate js code with the current commented out config in https://github.com/falsandtru/spica/blob/master/webpack.config.js. Any solutions to output .js files per module?

You use `import` and `export`. that is already esm

I'm not sure why you are trying to bundle an output js file per module. It doesn't matter where the code exists because webpack will do tree-shaking at the very last step. In other words, for you, simply doing tsc and letting projects import `dist` will allow their webpack to do treeshaking (provided that you are using esm)

https://webpack.js.org/guides/tree-shaking/ 

Here is a relevant link for webpack's tree-shaking

Should I try a PR for this?

**Comment by falsandtru** [comment]
> You use import and export. that is already esm

Ah, I thought you want .mjs files.

> I'm not sure why you are trying to bundle an output js file per module.

To individually import each module like `import 'spica/global'` to reduce file size.

> Should I try a PR for this?

Of course if you output umd-style js files per module without bundling. If webpack just outputs js files without bundling, we has no problem. https://github.com/webpack/webpack/issues/5866 is for this problem. TypeScript's umd was not enough.

**Comment by falsandtru** [comment]
Uh no, UMD may be not required. The important thing is to unify the build method with webpack. So I want to avoid annoying bundling of webpack in this package.

**Comment by nopeless** [comment]
Ok, I'll look into this issue tomorrow and see what I can come up with, thanks for the help and maintaining this repository by yourself
