### ISSUE TITLE
compare equal function can be optimized

### ISSUE THREAD

**Issue by nopeless** [falsandtru/spica#2]
`return a === b || a !== a && b !== b;` should be a faster solution for most cases since it is rather rare for both parameters to be `NaN`

Also, this library was really fun to read. Do you have a mail or social network id?

**Comment by falsandtru** [comment]
The number of worst-case comparisons is increased by one. The amortized number of comparisons is also increased because comparisons generally have more failures than successes.

**Comment by nopeless** [comment]
I understand your rationale now. I personally try to avoid NaN at all costs, making the final comparison (3 comparisons) impossible to reach.
