### ISSUE TITLE
Type errors from `type.ts`

### ISSUE THREAD

**Issue by EnixCoda** [falsandtru/spica#5]
Hi, I installed this package as it is a dependency of `pjax-api`. When trying to process it with TypeScript, below errors arose.

## Error 1

```
ERROR in ./node_modules/spica/type.ts:242:7
TS2304: Cannot find name 'assert'.
    240 |     case 'object':
    241 |       if (value === null) return 'null';
  > 242 |       assert(value = value as object);
        |       ^^^^^^
    243 |       const tag: string = (value as object)[Symbol.toStringTag];
    244 |       if (tag) return tag;
    245 |       switch (ObjectGetPrototypeOf(value)) {
```

I am wondering where the `assert` came from and why was it expected to be globally available.

## Error 2

```
ERROR in ./node_modules/spica/type.ts:243:27
TS7053: Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type '{}'.
  Property '[SymbolConstructor.toStringTag]' does not exist on type '{}'.
    241 |       if (value === null) return 'null';
    242 |       assert(value = value as object);
  > 243 |       const tag: string = (value as object)[Symbol.toStringTag];
        |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    244 |       if (tag) return tag;
    245 |       switch (ObjectGetPrototypeOf(value)) {
    246 |         case ArrayPrototype:
```

I tried to switch to the same TypeScript version as this project is using (5.4.5) but the error still exists.

**Comment by EnixCoda** [comment]
BTW, I see lots of `*.test.ts` files, readme files, and webpack config files of this project published onto NPM. Is that expected as well?

https://www.npmjs.com/package/spica?activeTab=code

<img width="1197" alt="image" src="https://github.com/falsandtru/spica/assets/7480839/a238c3e1-271b-4cad-9ccf-22b4e9197390">

**Comment by falsandtru** [comment]
Fixed.
